name: MacOS Golang build and test

on: [push]

jobs:
  macos-test:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ["macos-14"]
        go-version: ["1.21.x", "1.22.x"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        shell: bash
        run: go version

      - name: Golang test
        shell: bash
        run: |
          go test -v ./...
