name: Go tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go (from go.mod)
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run tests
        run: go test ./...
      - name: Run tests (short + race)
        run: go test -short -race ./...
      - name: KEM Benchmark tests
        run: cd kem/schemes && go test -v -bench=. -run Benchmark
